@echo off
echo Cleaning and rebuilding AutoDubber containers...
echo.
echo Stopping existing containers...
docker-compose down -v
echo.
echo Removing old images...
docker-compose rm -f
echo.
echo Building fresh containers...
docker-compose build --no-cache
echo.
echo Starting AutoDubber...
docker-compose up 